baseURL = "https://nwforrer.github.io/"
languageCode = "en-us"
title = "nick forrer"
theme = "charaka"
pygmentsCodeFences = true
pygmentsStyle = "dracula"

[params]

[[params.social]]
url = "https://github.com/nwforrer"
fa_icon = "fab fa-github"

[[params.social]]
url = "/index.xml"
fa_icon = "fas fa-rss"
