baseURL = "https://nwforrer.github.io/"
languageCode = "en-us"
title = "nick forrer"
theme = "ezhil"
pygmentsStyle = "emacs"
pygmentsCodeFences = true

[taxonomies]
category = "categories"
tag = "tags"

[params]
subtitle = "Game development and Lisp related posts"
featherIconsCDN = true
disableDisqusTypes = ["posts"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Roguelike Tutorials"
url = "/categories/roguelike-tutorial"
weight = 2

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nwforrer"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"
