baseURL = "https://nwforrer.github.io/"
languageCode = "en-us"
title = "nick forrer"
theme = "charaka"
pygmentsCodeFences = true

[params]

[[params.social]]
url = "https://github.com/nwforrer"
fa_icon = "fab fa-github"
